apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-etcd-backup
  labels:
    app: {{ .Chart.Name }}-{{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  schedule: "{{ .Values.backupParameters.backupSchedule }}"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etcdctl
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            env:
            - name: ETCDCTL_API
              value: "3"
            - name: ETCDCTL_CERT
              value: "/certs/etcd.pem"
            - name: ETCDCTL_KEY
              value: "/certs/etcd-key.pem"
            - name: ETCDCTL_CACERT
              value: "/certs/ca.pem"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ETCDCTL_ENDPOINTS
              value: "https://$(NODE_NAME):2379"
            command:
            - /bin/etcd-backup.sh
            volumeMounts:
            - name: etcd-certs
              mountPath: /certs
            - name: backup-dir
              mountPath: /data
            - name: configmap-volume
              mountPath: /bin/etcd-backup.sh
              readOnly: true
              subPath: etcd-backup.sh

          volumes:
          - name: etcd-certs
            hostPath:
                    #path: /etc/cfc/conf/etcd
              path: /etc/etcd/ssl/
          - name: backup-dir
            persistentVolumeClaim:
              claimName: {{ .Values.pvc.backupEtcdPvc }}
          - name: configmap-volume
            configMap:
              defaultMode: 0700
              name: {{ .Release.Name }}-etcd-backup
          

          tolerations:
          - effect: NoSchedule
            key: dedicated
            operator: Exists

          nodeSelector:
            etcd: "true"

          restartPolicy: "Never"
