# Default values for backup-etcd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: registry.cn-shenzhen.aliyuncs.com/liyu-hub/backup-etcd
  tag: 3.2.24
  pullPolicy: IfNotPresent

## Persistence enabled by default
## global persistence settings
persistence:
  enabled: true
  useDynamicProvisioning: false

pvc:
  backupEtcdPvc: backup-etcd-data-pvc

backupVolume:
  ## Specify the name of the Existing Claim to be used by your application
  existingClaimName: ""
 
  ## Specify the name of the StorageClass
  ## empty string means don't use a StorageClass
  storageClassName: ""

  ## minimum Persistence Storage volume size of 1Gi
  size: 1Gi

backupParameters:
  ## Specify the backup schedule in Cron format
  backupSchedule: "30 23 * * *"
  ##backup save retention in days
  backupRetention: 15

